
version: "3.3"

services:
  db:
    container_name: mediaServerDb
    image: mongo:latest
    restart: always
    volumes:
      - ./mediaData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= MediaServer
    ports:
      - 27017:27017